services:
  postgres:
    image: postgres:15-alpine
    container_name: expense_postgres
    environment:
      POSTGRES_DB: expense_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d expense_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: expense_api
    ports:
      - "8080:8080"
    environment:
      - DB_URL=postgres://postgres:password@postgres:5432/expense_db?sslmode=disable
      - PORT=8080
      - ENV=development
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 