services:
  - type: web
    name: expense-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DB_URL
        fromDatabase:
          name: expense-postgres
          property: connectionString
      - key: PORT
        value: 8080
      - key: ENV
        value: production
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: expense-postgres
    databaseName: expense_db
    user: expense_user
    plan: free 