name: Deploy to DigitalOcean App Platform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Test application
      run: |
        go mod download
        go test ./...
        
    - name: Deploy to DigitalOcean
      uses: digitalocean/app_action@main
      with:
        app_name: expense-api
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        images: '[{"name":"expense-api","registry_type":"DOCKER_HUB","registry":"your-dockerhub-username","tag":"latest"}]' 