name: Deploy to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Test application
      run: |
        go mod download
        go test ./...
        
    - name: Build application
      run: |
        go build -o main .
        
    - name: Deploy to Render
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        # This will trigger Render's auto-deploy
        echo "Deployment triggered to Render"
        echo "Make sure you have connected your GitHub repo to Render"
        echo "and set up the RENDER_TOKEN and RENDER_SERVICE_ID secrets" 